import { pgTable, text, serial, boolean } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";

export const users = pgTable("users", {
  id: serial("id").primaryKey(),
  walletAddress: text("wallet_address").notNull().unique(),
  isConnected: boolean("is_connected").default(false),
});

export const insertUserSchema = createInsertSchema(users).pick({
  walletAddress: true,
  isConnected: true,
});

export type User = typeof users.$inferSelect;
export type InsertUser = z.infer<typeof insertUserSchema>;

// API types
export type ConnectWalletRequest = {
  walletAddress?: string; // Optional, can be generated by backend for demo
};

export type ConnectWalletResponse = User;
